- deploy-prod.sh
Please advise if I'm using the wrong port
> Use port 80 for deployment

- client/src/components/HomeText.tsx
> Update landing page text

- client/package.json
- client/src/components/HomeText.tsx
- client/src/components/SearchResult.tsx
- client/src/components/navigation/Footer.tsx
- client/src/components/navigation/Navbar.tsx
- client/yarn.lock
Added Github buttons to footer and updated the homepage text to include the date of the newest dataset.
Fixes #11
> Add Github button and latest dataset date

- client/src/components/navigation/Navbar.tsx
> Add Feedback form link

- client/src/components/HomeText.tsx
- scripts/update-index.sh
> Update index to April 10 release

- api/app/routers/search.py
* Fixed some bugs from very rare errors
> Fix bugs with highlighting and searcher

- api/.env.sample
- api/app/modeling/__init__.py
- api/app/modeling/decode.py
- api/app/modeling/serialize.py
- api/app/services/ranker.py
- api/app/settings.py
- api/requirements.txt
Verified to be the same this time. As it turns out, the TensorFlow implementation was doing this weird tokenization where it was truncating the EOS token if the input exceeded the maximum length of 256.
Before:
```bash
QUERY="incubation%20time%20of%20covid"; diff <(curl -s "http://localhost:8001/api/search?query=$QUERY" | jq ".[].title") <(curl -s "http://localhost:8000/api/search?query=$QUERY" | jq ".[].title")
3d2                                                                                                         
< "Estimation of incubation period distribution of COVID-19 using disease onset forward time: a novel cross-sectional and forward follow-up study"
4a4                                    
> "Estimation of incubation period distribution of COVID-19 using disease onset forward …
```
> Port T5 ranker model from TensorFlow to PyTorch

- api/app/routers/search.py
- api/app/util/logging.py
- client/src/components/HomeText.tsx
* Added a `request_ip` field to the logs with the request IP
* Added Ralph to the home page
* Fixes #29, fixes #30
> Log IP address and update homepage text

- client/src/components/HomeText.tsx
- scripts/update-index.sh
* Update indexes for April 24 and landing page text (fixes #43 and fixes #44)
> Update index and landing page

- api/app/main.py
- api/app/models.py
- api/app/routers/related.py
- api/app/routers/search.py
- api/app/services/relatedHelper.py
- api/app/services/related_searcher.py
- api/app/settings.py
- api/app/util/request.py
- api/requirements.txt
- scripts/update-index.sh
Example: http://127.0.0.1:8000/api/related/bf2jg3qy?pageNumber=2
> New /api/related/{uuid} Endpoint

- client/src/components/pages/HomePage/HomeText.tsx
- Per title, following alphabetical order.
> Add x65han to landing page

- scripts/update-index.sh
- Update the Lucene index and HNSW index for CORD-19 upon the latest data drop on May 1st.
- Tested on the dev server with a new article titled `Loss-of-function tolerance of enhancers in the human genome`.
> [05-01] Update CORD-19 Index

- hnsw/helper.py
- hnsw/indexHNSW.py
- scripts/update-index.sh
- Add HNSW Indexing Logic to Covidex/
> Add HNSW Indexing Logic

- scripts/update-index.sh
> Update 05/12 Anserini index

- api/app/routers/related.py
- api/app/routers/search.py
- api/app/util/request.py
- scripts/deploy-prod.sh
- scripts/update-index.sh
> 05/19 Index Update and Fixes

- client/src/components/pages/HomePage/HomeText.tsx
- scripts/update-index.sh
> CORD-19 06/12 update

- scripts/update-anserini-index.sh
- Need to pull submodules for eval
> Pull submodules in index update script

- scripts/update-anserini-index.sh
Avoid manually clearing disk space
> Delete extra indexes in update script

- api/app/services/searcher.py
- client/src/components/pages/HomePage/HomeText.tsx
- client/src/shared/Constants.ts
Temporarily removing the Trialstreamer vertical
> Comment out Trialstreamer vertical

- client/src/components/navigation/Navbar.tsx
- client/src/components/pages/HomePage/HomeText.tsx
Future-proofing to reduce need for future updates.
> Updated text on Covidex landing page

- README.md
Without this fix , this server does not work with http.
> Fix rerouting instructions

- api/.env.sample
- api/app/routers/search.py
- api/app/services/highlighter.py
- api/app/services/ranker.py
- api/app/services/searcher.py
- api/app/settings.py
- api/requirements.txt
Updating the pygaggle dependency to a newer version, installing the most recent version from git because the most recent release in pip have some bugs that were already fixed in the git version of pygaggle.
With the update, some minor adjustments in the code were necessary.
> Updating covidex to use pygaggle 0.0.3.1
